@WebApiAuthentication.Api_HostAddress = https://localhost:7277

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApiAuthentication.Api_HostAddress}}/account/login/
Accept: application/json
Content-type: application/json
{
   "Username":"Brian",
   "Password": "Pluralsight"
}